name: Release
on:
  push:
    branches:
      - feather-mappings
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build publish --stacktrace

      - name: Clone aabric-libraries repo
        uses: actions/checkout@v4
        with:
          repository: floofyplasma/aabric-libraries
          token: ${{ secrets.WORKFLOW_TOKEN }}
          path: aabric-libraries

      - name: Copy published artifacts to repo
        run: |
          cp -r build/dist/* aabric-libraries/

      - name: Commit and push changes
        run: |
          cd aabric-libraries
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update published artifacts from ${{ github.sha }}" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
